export const researchReleases = [
  {
    slug: 'inverse-dynamics-model',
    source: 'crowd_cast_idm',
    number: '06',
    title: 'Annotating Unlabeled Screencasts with an IDM',
    shortTitle: 'Annotating Unlabeled Screencasts with an IDM',
    description: "We train an inverse dynamics model on crowd-cast's action-labeled dataset, yielding a model that recovers key presses, mouse clicks, cursor movements, and scroll events from unlabeled videos. Trained exclusively on macOS, the model outperforms orders-of-magnitude larger off-the-shelf models and generalizes to Windows and Linux. Along with the model, we openly release 600 hours of IDM-annotated screencasts.",
    summary: 'An inverse dynamics model trained to recover raw input events from screen recordings, released alongside 600 hours of action-labeled screencasts.',
    date: 'June 16, 2026',
    dateShort: 'Jun 16, 2026',
    authors: ['p(doom) Team'],
    category: 'Models + data',
    kind: 'Release',
    media: { type: 'image', src: '/assets/releases/idm.webp' },
  },
  {
    slug: 'crowd-cast',
    source: 'crowd_cast',
    number: '05',
    title: 'crowd-cast: Crowd-Sourcing Action-Annotated Long-Horizon Digital Labour',
    shortTitle: 'Capturing Long-Horizon Human Work',
    description: 'We introduce crowd-cast, a privacy-preserving desktop application that allows anyone to participate in crowd-sourcing an action-annotated long-horizon behaviour-cloning dataset of computer work.',
    summary: 'The largest long-horizon screencast dataset in the world, and open-source infrastructure for action-annotated crowd-sourcing.',
    date: 'February 2, 2026',
    dateShort: 'Feb 2, 2026',
    authors: ['Franz Srambical', 'Mihir Mahajan', 'Alfred Nguyen', 'Stefan Bauer'],
    category: 'Data infrastructure',
    kind: 'Release',
    media: { type: 'image', src: '/assets/releases/crowd-cast.webp' },
  },
  {
    slug: 'crowd-code',
    source: 'crowd_code_2',
    number: '04',
    title: 'crowd-code 2.0: Crowd-Sourcing Long-Horizon Human SWE Traces',
    shortTitle: 'Capturing Long-Horizon Human-Agent Cowork',
    description: 'We introduce crowd-code 2.0, a complete redesign of crowd-code: a VS Code / Cursor extension for crowd-sourcing software engineering traces as action-observation rollouts. Install once, and forget about it.',
    summary: 'More than six months of software-engineering traces across 25 people, with infrastructure for capturing human-agent work.',
    date: 'January 15, 2026',
    dateShort: 'Jan 15, 2026',
    authors: ['Alfred Nguyen', 'Mihir Mahajan', 'Franz Srambical', 'Stefan Bauer'],
    category: 'Data infrastructure',
    kind: 'Release',
    media: { type: 'image', src: '/assets/releases/crowd-code.webp' },
  },
  {
    slug: 'agi-cast',
    source: 'agi_cast',
    number: '03',
    title: 'AGI-CAST: Making Agents Work Like Humans',
    shortTitle: '600 Hours of AGI Research',
    description: 'We introduce AGI-CAST, a continually growing dataset of unlabeled screen recordings of AGI research.',
    summary: 'A continually growing, openly released dataset of long-horizon screen recordings of AGI research.',
    date: 'November 2, 2025',
    dateShort: 'Nov 2, 2025',
    authors: ['Franz Srambical'],
    category: 'Dataset',
    kind: 'Release',
    media: { type: 'image', src: '/assets/releases/agi-cast.webp' },
  },
  {
    slug: 'jasmine',
    source: 'jasmine',
    number: '02',
    title: 'Jasmine: A Simple, Performant and Scalable JAX-based World Modeling Codebase',
    shortTitle: 'Jasmine: A JAX-based World Modeling Codebase',
    description: 'We introduce Jasmine, a production-ready JAX-based world modeling codebase for learning from unlabeled videos. Scale from single hosts to hundreds of xPUs thanks to XLA.',
    summary: 'A production-ready JAX-based world modeling codebase and the largest open dataset of Minecraft Let\'s Plays for learning from unlabeled video.',
    date: 'August 5, 2025',
    dateShort: 'Aug 5, 2025',
    authors: ['Mihir Mahajan', 'Alfred Nguyen', 'Franz Srambical', 'Stefan Bauer'],
    category: 'Infrastructure',
    kind: 'Release',
    media: { type: 'image', src: '/assets/releases/jasmine.webp' },
  },
  {
    slug: 'crowd-code-original',
    source: 'crowd_code',
    number: '01',
    title: 'Crowd-Sourcing A Dataset To Make Agents Code Like Humans',
    shortTitle: 'Capturing Long-Horizon Human Software Engineering',
    description: 'We introduce crowd-code, a VS Code/Cursor extension that allows anyone to participate in crowd-sourcing a software engineering dataset to eventually finetune models on. Install once, and forget about it.',
    summary: 'Open-source infrastructure for crowd-sourcing a dataset of human software-engineering traces.',
    date: 'June 22, 2025',
    dateShort: 'Jun 22, 2025',
    authors: ['Franz Srambical', 'Mihir Mahajan'],
    category: 'Data infrastructure',
    kind: 'Release',
    media: { type: 'image', src: '/assets/releases/crowd-code-original.webp' },
  },
]

export const researchPosts = [
  {
    slug: 'ppo-is-off-policy',
    source: 'ppo_off_policy',
    title: 'PPO Is An Off-Policy Algorithm',
    description: 'PPO is commonly referred to as an on-policy algorithm. We argue that this is confusing, and show that truly on-policy PPO reduces to vanilla policy gradient REINFORCE with baseline.',
    date: 'April 29, 2025',
    dateShort: 'Apr 29, 2025',
    authors: ['Franz Srambical', 'Mihir Mahajan'],
    category: 'Reinforcement learning',
    kind: 'Research note',
  },
  {
    slug: 'jax-value-assertions',
    source: 'jax_assert',
    title: 'Performance-degradation Free Value Assertions in JAX',
    description: 'Traditional value assertions in jitted JAX lead to performance degradation. A new, not yet public, JAX API fixes this.',
    date: 'March 26, 2025',
    dateShort: 'Mar 26, 2025',
    authors: ['Franz Srambical'],
    category: 'Infrastructure',
    kind: 'Research note',
  },
  {
    slug: 'ppo-monte-carlo-advantage-estimation',
    source: 'ppo',
    title: 'PPO Is Secretly Using Monte Carlo Advantage Estimation In LLM Post-Training',
    description: 'When using PPO in LLM post-training, hyperparameter settings turn Generalized Advantage Estimation into Monte Carlo Advantage Estimation.',
    date: 'February 12, 2025',
    dateShort: 'Feb 12, 2025',
    authors: ['Franz Srambical'],
    category: 'Reinforcement learning',
    kind: 'Research note',
  },
  {
    slug: 'neural-networks-ood',
    source: 'thesis',
    title: 'Neural Networks Do Not Generalize Out-of-Distribution',
    description: 'Neural networks are mean-seeking. They work well when you run inference on data points that lie around the mean of their training data. They embarrassingly fail otherwise.',
    date: 'September 26, 2024',
    dateShort: 'Sep 26, 2024',
    authors: ['Franz Srambical', 'Mihir Mahajan'],
    category: 'Roadmap',
    kind: 'Research note',
  },
  {
    slug: 'beyond-the-causal-mask',
    source: 'causal_mask',
    title: 'Going Beyond the Causal Mask in Language Modeling',
    description: 'Although ubiquitously used in large-scale language modeling, the necessity of the causal mask is seldom questioned in the literature. Why do we really need the causal mask?',
    date: 'June 8, 2024',
    dateShort: 'Jun 8, 2024',
    authors: ['Franz Srambical'],
    category: 'Language modeling',
    kind: 'Research note',
  },
  {
    slug: 'adaptive-compute-transformer',
    source: 'act',
    title: 'ACT: Adaptive Compute Transformer',
    description: 'Large language models exhibit remarkable reasoning capabilities with scale. However, a fundamental flaw of current-generation transformer-based language models is their uniform allocation of compute per token.',
    date: 'December 7, 2023',
    dateShort: 'Dec 7, 2023',
    authors: ['Mihir Mahajan', 'Franz Srambical'],
    category: 'Language modeling',
    kind: 'Research note',
  },
]

export const externalPublications = [
  {
    title: 'Jasmine: A Simple, Performant and Scalable JAX-based World Modeling Codebase',
    dateShort: 'Oct 30, 2025',
    category: 'World modeling',
    kind: 'arXiv',
    href: 'https://arxiv.org/abs/2510.27002',
  },
]

export const allResearch = [...researchReleases, ...researchPosts]

export const researchBySlug = Object.fromEntries(allResearch.map((item) => [item.slug, item]))

export const legacyResearchRoutes = Object.fromEntries(
  allResearch.map((item) => [`${item.source}.html`, `/research/${item.slug}`]),
)

export function researchHref(item) {
  return `/research/${item.slug}`
}
